language: node_js
node_js:
- '0.12'
before_script:
- npm install
script:
- npm test
notifications:
  slack:
    secure: fi3p/QndEwWemnBm5xYR6scBir5hnYzpTxAhMFKVM0JzrMuzP7ovHeNttHV076SBvEhM7b4BVkZtXAtTaLlkgDBTatVsYBME+tS6Jq+qK41zgwLDdS9XhLI+dyu9CjubF8s4byT4KqLX6Fsl8kS/lujwg6f9aTIpqBPphVsw6+RVGjxUqG/q3lJOEWabLzO4o0prJqjEuv2Yi+6pPP+JEXLIGEwBdekoS3n0ZmA42IXBzq933Q34yzVNGHT8pe99E8ijm9Nmfrxxl2tU5OXZQIVM9YSIeTZ6/zNiXTvG2FttVHKPY5JhkAdXdcDXwJQGlIPYBi7NrVKDshYKDylKgHzMHp/MVGMUqX4efoasZaS05GAcPGc8EwL+0HzoZ5LuwFWKMd9xIBbZ2O2CFcf5LDZ6QWGjQdyMNSsWLbJydXGdGS+4SxZU58nzX6PlrWU+x1E9xZ/S1WkDNnXis8c3RLYOPLyJqWfo3AQrrWYzvISge1S2QiGIy9GSv/fZRhIwzaciPaSVkwpB93WsEMuSh/bwyXZa3g/yWblhyERDX9ZZr7fZ48HQIwnVK2OjYlVwGFhGuJnwMNN9eGWWLUugThRPCHmjGqXiy0WjThmenW6GDd6JARpH0JFLI7ua3XTcQ93ijO4Cl5dIKHArsmEATieJy7/54v311rJNlx8E1Ak=
